### ISSUE TITLE
Add token refreshing

### ISSUE THREAD

**Issue by parafoxia** [parafoxia/analytix#11]
**Summary**
Add the ability to refresh OAuth tokens automatically.

**The idea**
Refreshing tokens when needed (or just every time the application is started as there's no usage limit), will mean the user only needs to reauthorise after 200 days, rather than 1 hour.

**The ideal implementation**
Refresh token on startup would be easiest, however, this would not work for scheduled things. With that being said, analytix is not natively designed for this purpose anyways, so it will probably be fine. Version 3 will handle this.

**Contribution**
Do you want to contribute this feature yourself?
If someone doesn't PR something before I get the chance to work on it lmao.

**Comment by arndthassel** [comment]
Hello, I'm still a beginner but looking into this. Here is a (non-analytix) script where token refreshing seems to work:

`import os, pickle
import json
import pandas as pd
from pandas import json_normalize 

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

#PACKAGES FOR STORING OAUTH2 CREDENTIALS
from oauth2client import client 
from oauth2client import tools 
from oauth2client.file import Storage 

SCOPES = ['https://www.googleapis.com/auth/yt-analytics.readonly']

API_SERVICE_NAME = 'youtubeAnalytics'
API_VERSION = 'v2'

CLIENT_SECRETS_FILE = 'C:\\Path\To\Secrets.json' 


#GET OAUTH2 AUTHENTICATION AND STORE CREDENTIALS TO credential_sample.json
def get_authenticated_service(): 
    credential_path = os.path.join('./', 'credential_sample.json')
    store = Storage(credential_path)
    credentials = store.get()
    if not credentials or credentials.invalid:
        flow = client.flow_from_clientsecrets(CLIENT_SECRETS_FILE, SCOPES)
        credentials = tools.run_flow(flow, store)
    return build(API_SERVICE_NAME, API_VERSION, credentials=credentials)


#EXECUTE QUERY CODE AND PRINT RESULT
def execute_api_request(client_library_function, **kwargs):
  response = client_library_function(
    **kwargs
  ).execute()

  print(response)
  df = pd.DataFrame(response['rows'],columns=['day','estimatedMinutesWatched','views', 'likes', 'subscribersGained'])

  print(df)
  df.to_csv('output.csv', sep=',', encoding='utf-8')


if __name__ == '__main__':
  os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

  youtubeAnalytics = get_authenticated_service()
  execute_api_request(
      youtubeAnalytics.reports().query,
      
            ids='channel==XYZ',
      startDate='2021-02-01',
      endDate='2021-04-30',
      metrics='estimatedMinutesWatched,views,likes,subscribersGained',
      dimensions='day',
      sort='day'
  )
`

**Comment by parafoxia** [comment]
As it doesn't look as though there's anything that refreshes the token in there -- it largely seems to rely on storing the token, which analytix already does.

I remember your email saying that the token lasts about a week using this method, though I'm not sure how that's actually achieved, as refreshing should allow you 200 days of access.

analytix also doesn't rely on the Python API client.

**Comment by arndthassel** [comment]
I've noticed that the analytix token file comes with the following entry: 
"expires": 1644664627.5195115

Wonder if that has anything to do with it. I've tried changing the unix time in the file, saving and rerunning, but that didn't work. 

By the way, the token I'm using with the above script has been going strong since Feb 9 --> more than one week.

**Comment by parafoxia** [comment]
That time is when the API expires it -- changing it on your end won't do anything.

The analytix token file just stores information about the token -- once that time has passed it will realise it's expired and ask you for a new one.

**Comment by parafoxia** [comment]
Update on this -- the code base for this is fairly old, and I forgot it was using the `requests-oauthlib` library instead of just doing it itself. I think I can botch it in, but it will need a refactoring to work well -- version 3 will do this anyways.

**Comment by arndthassel** [comment]
Thanks for the update. Basically what you're saying is that it is not that
easy to change the OAuth2 functionality from what it is right now to the
one in the script I provided, right? Do you (roughly) know which files
would have to be reworked?


Am Do., 17. Feb. 2022 um 16:45 Uhr schrieb Ethan Henderson <
***@***.***>:

**Comment by parafoxia** [comment]
Sort of, yeah. I'm having some issues testing it but that might just be the OAuth servers having a fit.

I'm doing it without the stuff from the script though -- version 1 of analytix used the API client but version 2 dropped it in favour of a more manual approach for many many reasons lmao.

Good news is that I've got token refreshing working in the version 3 alpha (only problem is you can't retrieve any reports in it yet) d:

**Comment by parafoxia** [comment]
I've decided to bump this to the v3.0 release, as progress is coming along well, and it will just be easier than trying to botch something in that analytix wasn't designed to handle.

@arndthassel, if you want to give it a spin, you can find the code here: https://github.com/parafoxia/analytix/tree/task/rewrite. Alternatively, you can install it using `pip install git+https://github.com/parafoxia/analytix@task/rewrite`. It can't retrieve reports yet, but most of the validation steps have been implemented, and crucially, the token refreshing system is up and working, so if you wanna give it a shot, go for it.

I'll give you a holler when version 3 launches if you like.
