### ISSUE TITLE
Reports Retrieves Blank rows 

### ISSUE THREAD

**Issue by Shiffo0** [parafoxia/analytix#49]
### Steps to reproduce

import analytix
from analytix import Client

# Let's enable the logger so we can see what's going on.
analytix.enable_logging()

if __name__ == "__main__":
    with Client("secrets_youtube_data.json") as client:
        report = client.retrieve_report(
            dimensions=("video",),
            metrics=("estimatedMinutesWatched", "views", "likes", "subscribersGained"),
            max_results=10,
            sort_options=("-estimatedMinutesWatched",),
        )
        report.to_csv("top_10_watched_videos.csv")

### Expected behaviour

list of 10 video's sorted by views

### Current behaviour

blank csv file with only headers.

### analytix version

4.1.3

### Extra information

Information:
 • Python version: 3.9.12 (CPython)
 • Operating system: Windows (10)
 • Installed in: C:\Users\s.piroe\Anaconda3\lib\site-packages\analytix

### Additional information

1,748,694ms [ INFO    ] analytix.oidc: Secrets loaded (type: installed)!
1,748,703ms [ INFO    ] analytix.oidc: Tokens loaded!
1,748,765ms [ INFO    ] analytix.shard: Access token does not need refreshing
1,748,766ms [ INFO    ] analytix.client: Authorisation complete!
1,748,766ms [ INFO    ] analytix.queries: Validating request
1,748,769ms [ INFO    ] analytix.queries: Getting data between 2023-01-22 and 2023-02-19
1,748,769ms [ INFO    ] analytix.queries: Report type determined as 'Top videos by region'
1,748,770ms [ INFO    ] analytix.queries: Request OK!
1,748,981ms [ INFO    ] analytix.shard: Created report of shape (0, 5)!

### Checklist

- [X] I have searched the issue tracker for duplicate issues and couldn't find any. If this is a follow-up issue, I have specified as such.

**Comment by Shiffo0** [comment]
i think that I understand what is causing this issue.
I have 3 accounts set-up to my Gmail account and with my authorization process I did not select my actual YouTube account.
So the reason why the blanks are showing up is because I authorized with the wrong account.

**Comment by Shiffo0** [comment]
Confirmed that this was causing the issue! Problem solved!

**Comment by parafoxia** [comment]
Glad you got it sorted!
