### ISSUE TITLE
Data fetch for more than 200 videos

### ISSUE THREAD

**Issue by santoshinresideo** [parafoxia/analytix#59]
### Summary

Currently in a single go data can be fetched for 200 videos. However if there are more than 200 videos then indexing needs to be done, which is okay to do. However, there is no way to find max number of videos present in the channel so that indexing can be done.  

### Why?

If a channel has more than 200 videos it is difficult to fetch the data. 

### Contribution

- [ ] I wish to contribute this feature.

### Checklist

- [X] I have searched the issue tracker for duplicate issues and couldn't find any. If this is a follow-up issue, I have specified as such.

**Comment by parafoxia** [comment]
Can you share what you're doing at the moment to get around this, i.e. with the indexing stuff? I think I understand what you mean, but just want to confirm.

As for the total video count, there's no way to get that information out of the Analytics API afaik. You'd need to query the Data API using a different library first to get that info.

**Comment by santoshinresideo** [comment]
This is what I am doing. If further required then, I can merge the CSV files. Till now this is not a requirement. But once the channel has more than 200 videos the code will not work as expected. 

```
from analytix import Client  # or AsyncClient
from datetime import date, datetime, timedelta

def get_report(start_index):
    client = Client("secret.json")
    report = client.retrieve_report(
        dimensions=("video",),
        max_results=20,
        sort_options=("-views",),
        end_date= date.today(),
        currency="EUR",
        start_index=start_index,
        start_date=(date.today() - timedelta(days=365))
    )
    file_name = "analytics"+ str(start_index) +".csv"
    report.to_csv(file_name)
    return file_name

for i in range(2):
    get_report(i+1)
```

Now I understand that, it is not achievable to get max number of videos using Analytics API. But as you said there are other ways to do so. Thanks for that.

**Comment by parafoxia** [comment]
Yeah that's pretty much how you'd have to do it. You could probably simplify it a little by using merging Pandas DataFrames together using `report.to_pandas` and `pd.concat` then exporting it all as one CSV. I might have a think about whether I can reasonly make a utility function/method that does it behind the scenes, though I'm not 100% sure atm where it could go.

**Comment by santoshinresideo** [comment]
I am not sure if this should be done as I am new to this but there can be a flow like this.

1. User enables a flag to go for a index looping 
2. The loop will run till it gets this exception/error `analytix.errors.InvalidRequest: the start index is too high`
3. At the end as you said it will merge all the data. 

If this is something not doable or shouldn't be done then I think that's it. We can close the issue.

**Comment by parafoxia** [comment]
So I've had a bit of a look into this, and API constraints on YouTube's end actually make this impossible. You can't get the 201st result of the query, even if you program the start index to take you there; it just returns a `BadRequest` (once analytix's verification systems are turned off).
