### ISSUE TITLE
Token expires after a week

### ISSUE THREAD

**Issue by santoshinresideo** [parafoxia/analytix#60]
### Summary

I am running the below code every day. However after a week or so the token expires and I had to renew the access token. It may be basic thing, However I am struggling with it. Can you please help me ? 

```python
def get_report():
    client = Client("secret.json")
    report = client.retrieve_report(
        dimensions=("video",),
        max_results=200,
        sort_options=("-views",),
        end_date= date.today(),
        currency="EUR",
        start_date=(date.today()- timedelta(days=365))
    )
    file_name = "analytics.csv"
    report.to_csv(file_name)
    return file_name
```

### Why?

I think this is because the token expiry is set to a less time

### Contribution

- [ ] I wish to contribute this feature.

### Checklist

- [X] I have searched the issue tracker for duplicate issues and couldn't find any. If this is a follow-up issue, I have specified as such.

**Comment by parafoxia** [comment]
Refresh tokens expire after a week if your application is in "Testing" mode. The only way to make it last longer is to publish your application.

https://developers.google.com/identity/protocols/oauth2#expiration

I'm gonna close this as there's nothing I can do on my end, but feel free to leave further comments if you want to discuss this further.

**Comment by santoshinresideo** [comment]
It says, I have to publish the application. To publish it, I have to go through whole verification process. Is there any alternative way ?
